### ISSUE TITLE
Resize box overlaps scroll bars if bars are only present for one dimension (vertical or horizontal)

### ISSUE THREAD

**Issue by bigmac44** [Sphinxxxx/cm-resize#2]
If no scrollbars are present or both vertical and horizontal bars are displayed there is not problem as they leave a margin in the bottom right corner.  However if only a vertical or only a horizontal scrollbar are present the bar will extend all the way to the bottom right corner of the code mirror area where the resize box is drawn.  This results in the bar and resize box overlapping.

**Comment by Sphinxxxx** [comment]
Thanks, fixed in v1.0.0
