### ISSUE TITLE
Script no longer available at https://unpkg.com/cm-resize@1.0.0

### ISSUE THREAD

**Issue by bigmac44** [Sphinxxxx/cm-resize#3]
It looks like the URL is now: https://unpkg.com/cm-resize@1.0.0/dist/cm-resize.js 

The readme should be updated to reflect that.  But existing apps break if they refer to the old url, so hopefully that can be fixed.

**Comment by Sphinxxxx** [comment]
Thanks, this is an issue with **unpkg** which hopefully will be fixed soon:
https://github.com/unpkg/unpkg.com/issues/156

**Comment by Sphinxxxx** [comment]
@bigmac44 Could you try this link, which should bring you to the new v1.0.1?

https://unpkg.com/cm-resize@1

**Comment by bigmac44** [comment]
Looks good.
