### ISSUE TITLE
capture viewport height/size

### ISSUE THREAD

**Issue by gregh3269** [Sphinxxxx/cm-resize#4]
Hello, is there a way I can capture the height/size of the viewport when the drag stops ( ie into a hidden field).

cm.getWrapperElement().offsetHeight gives the height.

Cheers Greg

**Comment by Sphinxxxx** [comment]
Hello! This plugin doesn't trigger any events like that, but you could *continuously* capture the size using CodeMirror's own events. For example:

```javascript
var myCM = ...
cmResize(myCM);
myCM.on('update', function(cm) {
    var size = cm.getScrollInfo(),
        width = size.clientWidth,    //or .width depending on what you need
        height = size.clientHeight;  //or .height
        ...
});
```

**Comment by gregh3269** [comment]
ok great thanks, should have though of this myself!
